spring.application.name=realestate-portal

# URL fallback to localhost and port 3307
spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3307}/${MYSQLDATABASE:realstate_db}

# USER fallback to 'root' (or your local MySQL username)
spring.datasource.username=${MYSQLUSER:root}

# PASSWORD fallback directly to your local MySQL password string
spring.datasource.password=${MYSQLPASSWORD:ak123}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update   
spring.jpa.show-sql=true              
spring.jpa.properties.hibernate.format_sql=true